#!/bin/sh

gcc generate_instances.c -o generate_instances

gcc solve_dp.c -o solve_dp

gcc solve_greedy1.c -o solve_greedy1

gcc solve_greedy2.c -o solve_greedy2

./generate_instances 2 30 3 100 instances.txt

./solve_dp instances.txt results_dp.txt

./solve_greedy1 instances.txt results_greedy1.txt

./solve_greedy2 instances.txt results_greedy2.txt

python3 compare_algos_plot.py results_dp.txt results_greedy1.txt results_greedy2.txt